INSERT INTO Usuarios (nombre, apellido, nombre_usuario, token, contrasena, ciudad, sexo, estado_civil, tipo_empresa, direccion, id_tipo_usuario) VALUES
('Juan', 'Pérez', 'juanperez', 'token123', 'contraseña123', 'Madrid', 'Masculino', 'Soltero', 'privada', 'Calle Mayor, 1', 1),
('María', 'García', 'mariagarcia', 'token456', 'password456', 'Barcelona', 'Femenino', 'Casada', 'pública', 'Calle Gran Vía, 2', 2),
('Carlos', 'López', 'carloslopez', 'token789', 'secreto789', 'Valencia', 'Masculino', 'Divorciado', 'privada', 'Calle Colón, 3', 3),
('Ana', 'Martínez', 'anamartinez', 'tokenabc', 'claveabc', 'Sevilla', 'Femenino', 'Soltera', 'pública', 'Calle Sierpes, 4', 4),
('Pedro', 'Rodríguez', 'pedrorodriguez', 'tokenxyz', 'contraseñaXYZ', 'Zaragoza', 'Masculino', 'Casado', 'privada', 'Calle San Miguel, 5', 5),
('Laura', 'Hernández', 'laurahernandez', 'tokendef', 'passwordDEF', 'Málaga', 'Femenino', 'Soltera', 'pública', 'Calle Larios, 6', 1),
('Javier', 'Gómez', 'javiergomez', 'tokendgh', 'secretoDGH', 'Bilbao', 'Masculino', 'Casado', 'privada', 'Calle Ercilla, 7', 2),
('Sofía', 'Díaz', 'sofiadiaz', 'tokenijk', 'claveIJK', 'Alicante', 'Femenino', 'Divorciada', 'pública', 'Calle Mayor, 8', 3),
('Diego', 'Torres', 'diegotorres', 'tokenlmn', 'passwordLMN', 'Córdoba', 'Masculino', 'Soltero', 'privada', 'Calle Cruz Conde, 9', 4),
('Elena', 'López', 'elenalopez', 'tokenopq', 'secretoOPQ', 'Granada', 'Femenino', 'Casada', 'pública', 'Calle Reyes Católicos, 10', 5),
('Andrés', 'Martín', 'andresmartin', 'tokenrst', 'claveRST', 'Oviedo', 'Masculino', 'Soltero', 'privada', 'Calle Uría, 11', 1),
('Lucía', 'Ruiz', 'luciaruiz', 'tokenuvw', 'passwordUVW', 'Vigo', 'Femenino', 'Casada', 'pública', 'Calle Príncipe, 12', 2),
('Pablo', 'González', 'pablogonzalez', 'tokenxyz', 'secretoXYZ', 'Santander', 'Masculino', 'Divorciado', 'privada', 'Calle Burgos, 13', 3),
('Marina', 'Sánchez', 'marinasanchez', 'tokenabc', 'claveABC', 'Murcia', 'Femenino', 'Soltera', 'pública', 'Gran Vía, 14', 4),
('Roberto', 'Martínez', 'robertomartinez', 'tokendef', 'passwordDEF', 'Salamanca', 'Masculino', 'Casado', 'privada', 'Calle Zamora, 15', 5),
('Valeria', 'Hernández', 'valeriahernandez', 'tokendgh', 'secretoDGH', 'Burgos', 'Femenino', 'Soltera', 'pública', 'Calle Vitoria, 16', 1),
('Gabriel', 'Flores', 'gabrielflores', 'tokenijk', 'claveIJK', 'León', 'Masculino', 'Casado', 'privada', 'Calle Ordoño II, 17', 2),
('Carolina', 'Díaz', 'carolinadiaz', 'tokenlmn', 'passwordLMN', 'Tenerife', 'Femenino', 'Divorciada', 'pública', 'Avenida Tres de Mayo, 18', 3),
('Alejandro', 'López', 'alejandrolopez', 'tokenopq', 'secretoOPQ', 'Pamplona', 'Masculino', 'Soltero', 'privada', 'Calle Estafeta, 19', 4),
('Isabella', 'García', 'isabellagarcia', 'tokenrst', 'claveRST', 'Logroño', 'Femenino', 'Casada', 'pública', 'Calle Laurel, 20', 5);
