INSERT INTO Tipos_Pruebas (referencia, nombre, descripcion, fecha_ingreso, estado) VALUES
('REF001', 'Reconocimiento', 'Identificación inicial de activos y características del objetivo.', '2023-01-15', 'activado'),
('REF002', 'Análisis de Vulnerabilidad', 'Identificación y evaluación de vulnerabilidades en sistemas y redes.', '2023-02-20', 'activado'),
('REF003', 'Explotación', 'Uso de vulnerabilidades para ganar acceso no autorizado o privilegios elevados.', '2023-03-25', 'activado'),
('REF004', 'Escalar Privilegios', 'Técnicas para obtener acceso a recursos y permisos elevados en sistemas.', '2023-04-30', 'activado'),
('REF005', 'Enumeración', 'Recopilación de información detallada sobre el objetivo, como servicios disponibles y usuarios.', '2023-05-15', 'activado'),
('REF006', 'Ingeniería Social', 'Uso de técnicas psicológicas para obtener acceso no autorizado.', '2023-06-20', 'activado'),
('REF007', 'Pruebas de Aplicaciones Web', 'Evaluación de la seguridad de aplicaciones web en busca de vulnerabilidades.', '2023-07-25', 'activado'),
('REF008', 'Pruebas de Redes', 'Evaluación de la seguridad de redes para identificar vulnerabilidades y configuraciones incorrectas.', '2023-08-30', 'activado'),
('REF009', 'Pruebas de Sistemas Operativos', 'Evaluación de la seguridad de sistemas operativos para identificar configuraciones inseguras.', '2023-09-15', 'activado'),
('REF010', 'Pruebas de Seguridad Física', 'Evaluación de la seguridad física de instalaciones, edificios o centros de datos.', '2023-10-20', 'activado'),
('REF011', 'Pruebas de Phishing', 'Simulación de ataques de phishing para evaluar la preparación y respuesta de los usuarios.', '2023-11-25', 'activado'),
('REF012', 'Pruebas de Intrusión Interna', 'Simulación de ataques internos para evaluar la respuesta y detección de amenazas internas.', '2023-12-30', 'activado'),
('REF013', 'Pruebas de Cumplimiento', 'Evaluación para asegurar que los sistemas y procesos cumplan con normativas y estándares.', '2024-01-15', 'activado'),
('REF014', 'Pruebas de Seguridad Móvil', 'Evaluación de la seguridad de aplicaciones y dispositivos móviles en busca de vulnerabilidades.', '2024-02-20', 'activado'),
('REF015', 'Análisis Forense', 'Investigación y análisis de incidentes de seguridad para determinar su causa y alcance.', '2024-03-25', 'activado'),
('REF016', 'Pruebas de Penetración', 'Simulación de ataques reales para evaluar la resistencia de los sistemas y redes.', '2024-04-30', 'activado'),
('REF017', 'Monitoreo de Seguridad', 'Implementación y gestión de herramientas para la detección de amenazas en tiempo real.', '2024-05-15', 'activado'),
('REF018', 'Análisis de Logs', 'Revisión y análisis de registros de actividad para detectar incidentes de seguridad.', '2024-06-20', 'activado'),
('REF019', 'Evaluación de Configuraciones', 'Revisión y ajuste de configuraciones para mejorar la seguridad de sistemas y redes.', '2024-07-25', 'activado'),
('REF020', 'Auditoría de Seguridad', 'Revisión y evaluación independiente de controles de seguridad para garantizar su eficacia.', '2024-08-30', 'activado');
